---
title: "Homework 5"
author: "Dania Jafar"
date: "11/11/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```


```{r setup}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```
# Problem 1
```{r Problem 1}

#replacing missing values with the appropriate values 
replace_missing = function(x) {
  if (is.numeric(x)){ 
    x = replace_na(x, mean(x, na.rm = TRUE))}
   else if (is.character(x)) {
     x = replace_na(x,"virginica")}
  }
 #creating a table that shas the missing values filled in
fixed_iris = map(iris_with_missing, replace_missing) %>% 
  as_tibble() 
```

# Problem 2
```{r Problem 2}

files = list.files(path = "./data") 

data = data_frame(file_name = files) %>% 
    mutate(file_contents = map(file_name, ~read_csv(file.path("./data", .)))) %>%
  unnest() %>% 
pivot_longer(week_1:week_8, names_to = "week",
   values_to = "measurement") %>% 
  separate(file_name, sep = ".c", into = c("file_name", "remove")) %>% select(-remove) %>% 
  separate(file_name, into = c("group", "subject_id"), sep = "_") %>% 
  mutate(
    group = recode(group,
         `con` = "control",
         `exp` = "experimental")
    ) %>% 
mutate_all(~gsub("week_", "", .)) %>% 
  #convert week and measurement variables to numeric so they can be graphed correctly
mutate(week = as.numeric(week)) %>% 
mutate(measurement = as.numeric(measurement))
  
  #creating a plot that graphs week by measurement
data %>%
  ggplot(aes(x = week, y = measurement , color = group, group = subject_id)) + 
  geom_path() 
```
# Problem 3
```{r}
set.seed(50)
library(broom)
#setting up a regression model
prob3_regression = function(n = 30, beta0 = 2, beta1) {
sim_data = tibble(
x = rnorm(n),
y = 2 + beta1 * x + rnorm(30, 0, 50)
)

ls_fit = tidy(lm(y ~ x, data = sim_data)) %>% 
  filter(term == "x")

apple = tibble (
beta1_hat = ls_fit$estimate,
p_value = ls_fit$p.value
)
print(apple)
}
```


```{r}
sim_results = 
tibble(beta1 = c(1, 2, 3, 4, 5, 6)) %>% 
mutate(
output_list = map(.x = beta1, ~rerun(10, sim_regression(beta1 = .x))),
estimate_dfs = map(output_list, bind_rows)) %>% 
unnest(estimate_dfs) %>% 
select(beta1,beta1_hat,p_value)

sim_results %>% 
  ggplot(aes(x = beta1, y = beta1_hat)) + 
  geom_point()

#Now we are going to create a function for the proportion of times the null was rejected. 

proportion_reject = 
  sim_results %>% 
  group_by(beta1) %>%
  summarize((reject = length(p_value <0.05)) #at which p-value we want the function to reject
total = n()) %>% 
  mutate(proportion = reject/ total)


#I am going to now add a regression line 
ggplot(reject_proportion, aes(x = beta1, y = proportion)) + geom_point() + geom_smooth() + labs (y = "The Proportion the Null was Rejected", x = Number, title = "Power vs. Effect Size")


```




